name: nf-sbrnaseq

channels:
    - conda-forge
    - bioconda

dependencies:
    - python==3.12
    - pip
    - bioconda::bowtie2
    - bioconda::fastqc
    - bioconda::samtools
    - bioconda::sra-tools
    - bioconda::star
    - bioconda::subread
    - pip:
        - 'carabiner-tools[mpl,pd]>=0.0.4'
        - 'cutadapt>=5.0'
        - 'multiqc>=1.27'
        - 'numpy>=2.1.3'
        - 'scanpy[leiden]>=1.10.4'
        - 'umi_tools==1.1.6'