name: nf-sbrnaseq

channels:
    - conda-forge
    - bioconda

dependencies:
    - python>=3.8
    - pip
    - bioconda::bowtie2
    - bioconda::fastqc
    - bioconda::samtools
    - bioconda::subread
    - pip:
        - 'cutadapt>=4.0'
        - matplotlib
        - 'multiqc>=1.21'
        - numpy
        - pandas
        - 'umi_tools>=1.0'