name: nf-sbrnaseq

channels:
    - conda-forge
    - bioconda

dependencies:
    - python
    - pip
    - openjdk
    - cutadapt
    - bowtie2
    - subread
    - fastqc
    - multiqc
    - samtools
    - umi_tools